export { default as AvatarIcon } from './AvatarIcon.png';
export { default as Facebook } from './Facebook.png';
export { default as Instagram } from './Instagram.png';
export { default as Linkedin } from './Linkedin.png';
export { default as LogoIcon } from './Logo.png';
export { default as Menu } from './Menu.png';
export { default as Preview } from './Preview.png';
export { default as SearchIcon } from './Search.png';
export { default as Twitter } from './Twitter.png';
