export { default as CategoriesSection } from './CategoriesSection';
export { default as CompanySection } from './CompanySection';
export { default as CustomThemeProvider } from './CustomThemeProvider';
export { default as FilmCard } from './FilmCard';
export { default as FilmsList } from './FilmsList';
export { default as Footer } from './Footer';
export { default as Header } from './Header';
export { default as Logo } from './Logo';
export { default as Main } from './Main';
export { default as MetadataSection } from './MetadataSection';
export { default as SearchBar } from './SearchBar';
export { default as SearchSection } from './SearchSection';
export * from './UI';
