export { CategoriesSection } from './CategoriesSection';
export { CompanySection } from './CompanySection';
export { CustomThemeProvider } from './CustomThemeProvider';
export { ErrorBoundary } from './ErrorBoundary';
export { FilmCard } from './FilmCard';
export { FilmsList } from './FilmsList';
export { Footer } from './Footer';
export { FrameSkeletonLoader } from './FrameSkeletonLoader';
export { Header } from './Header';
export { Logo } from './Logo';
export { Main } from './Main';
export { MetadataSection } from './MetadataSection';
export { PopupPlayer } from './PopupPlayer';
export { SearchBar } from './SearchBar';
export { SearchSection } from './SearchSection';
export { SkeletonLoader } from './SkeletonLoader';
export { SkeletonLoadersList } from './SkeletonLoadersList';
export * from './UI';
